name: Keploy API Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-keploy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'
          mongodb-port: 27017

      - name: Create .env file
        run: cp .env.example .env
        working-directory: ./server

      - name: Install Server Dependencies
        run: npm install
        working-directory: ./server

      - name: Start Server in Background
        run: npm start &
        working-directory: ./server

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=64f653b9-6c94-4474-9fc4-1056d9a4f0e6 --base-path http://localhost:4000 --cloud